/*IMPORT ADVS DATASET*/;
PROC IMPORT DATAFILE="C:\Users\Documents\SAS Project Listing ADVS Raw data.xlsx"
OUT=WORK.ADVS
DBMS=XLSX REPLACE;
RUN;

DATA ADVS;
SET WORK.ADVS;
RUN;

/*IMPORT ADSL DATASET*/;
PROC IMPORT DATAFILE="C:\Users\project+notes\SAS Project Listing ADSL Raw data.xlsx"
OUT=WORK.ADSL
DBMS= XLSX REPLACE;
RUN;

DATA ADSL;
SET WORK.ADSL;
RUN;

PROC SQL;
CREATE TABLE ADSL_ADVS AS SELECT
ADVS.USUBJID, ADVS.TRTP, ADVS.TRTPN, ADVS.PARAM, ADVS.AVISIT, ADVS.AVISITN, ADVS.AVAL, ADSL.USUBJID,
ADSL.SEX, ADSL.AGE, ADSL.COUNTRY
FROM ADVS LEFT JOIN ADSL
ON ADVS.USUBJID= ADSL.USUBJID;
QUIT;

PROC FORMAT;
VALUE $GENDER 'M'='Male' 
              'F'='Female';
RUN;

/*CREATE THE REPORT BY USING PROC REPORT*/;

PROC REPORT DATA=ADSL_ADVS headline headskip SPLIT='.';
COLUMN (USUBJID SEX COUNTRY AGE TRTP TRTP TRTPN PARAM AVISIT AVISITN AVAL);
DEFINE USUBJID/ORDER 'Sunject Identifier';
DEFINE Sex/ORDER FORMAT=$GENDER.;
DEFINE Country/ORDER;
DEFINE Age/ORDER;
DEFINE TRTP/ORDER 'Planned Treatment';
DEFINE TRTPN/ORDER NOPRINT;
DEFINE PARAM/ORDER 'Parameter Description';
DEFINE AVISIT/ ORDER 'Analysis Visit';
DEFINE AVISITN/ORDER NOPRINT;
DEFINE AVAL/ORDER 'Analysis Value';
BREAK AFTER PARAM/SKIP;
COMPUTE BEFORE _Page_;
LINE @7 'BP3304-002' @200 '1-Vitals.SAS';
LINE '';
LINE '';
LINE @80 'Subject Vitals Signs Information-Listing';
LINE '';
ENDCOMP;
RUN;
